/**
 * Hub-and-Spoke: Blog → Ratgeber-Pillar (SEO-Masterplan Cluster-Zuordnung).
 */
export const blogPillarBySlug: Record<string, string> = {
  "dguv-vorschrift-2": "arbeitsschutz-unternehmen",
  "dguv-vorschriften-einfach-erklaert": "arbeitsschutz-unternehmen",
  "dguv-vorschrift-1-grundsaetze-praevention": "arbeitsschutz-unternehmen",
  "dguv-vorschrift-38-bauarbeiten": "sigeko-baustelle",
  "dguv-vorschrift-67-flurfoerderzeuge": "gefaehrdungsbeurteilung",
  "asr-a2-2-brandschutzhelfer": "brandschutz-betrieb",
  "bestellung-fachkraft-arbeitssicherheit": "arbeitsschutz-unternehmen",
  "unterweisung-arbeitsschutz-fristen": "arbeitsschutz-unternehmen",
  "jugendarbeitsschutz-jarbschg-einfach-erklaert": "arbeitsschutz-unternehmen",
  "jarbschg-arbeitszeit-ruhezeiten": "arbeitsschutz-unternehmen",
  "jarbschg-unterweisung-aushang-dokumentation": "arbeitsschutz-unternehmen",
  "jarbschg-verbotene-gefaehrliche-arbeiten": "gefaehrdungsbeurteilung",
  "mutterschutz-muschg-einfach-erklaert": "gefaehrdungsbeurteilung",
  "muschg-schutzfristen-arbeitszeit": "gefaehrdungsbeurteilung",
  "muschg-unzulaessige-taetigkeiten-schutzmasnahmen": "gefaehrdungsbeurteilung",
  "muschg-aushang-mitteilung-dokumentation": "gefaehrdungsbeurteilung",
  "teilhabe-sgb-ix-einfach-erklaert": "gefaehrdungsbeurteilung",
  "sgb-ix-beschaeftigungspflicht-ausgleichsabgabe": "gefaehrdungsbeurteilung",
  "sgb-ix-arbeitsplatz-gestaltung-gbu": "gefaehrdungsbeurteilung",
  "sgb-ix-schwerbehindertenvertretung-inklusionsbeauftragter": "arbeitsschutz-unternehmen",
  "akteure-arbeitsschutz": "arbeitsschutz-unternehmen",
  "betrsichv-einfach-erklaert": "gefaehrdungsbeurteilung",
  "trbs-einfach-erklaert": "gefaehrdungsbeurteilung",
  "trbs-1111-gefaehrdungsbeurteilung-arbeitsmittel": "gefaehrdungsbeurteilung",
  "trbs-1201-1203-pruefung-befaehigte-person": "gefaehrdungsbeurteilung",
  "trbs-2121-absturz-leitern": "gefaehrdungsbeurteilung",
  "trgs-einfach-erklaert": "gefaehrdungsbeurteilung",
  "trgs-400-gefaehrdungsbeurteilung-gefahrstoffe": "gefaehrdungsbeurteilung",
  "trgs-509-510-lagerung-gefahrstoffe": "gefaehrdungsbeurteilung",
  "trgs-528-schweisstechnische-arbeiten": "gefaehrdungsbeurteilung",
  "asr-einfach-erklaert": "arbeitsschutz-unternehmen",
  "asr-a6-bildschirmarbeit": "arbeitsschutz-unternehmen",
  "asr-a3-7-laerm-arbeitsplatz": "gefaehrdungsbeurteilung",
  "asr-a2-1-absturz-absturzsicherung": "arbeitsschutz-unternehmen",
  "asr-a4-3-erste-hilfe-arbeitsstaette": "arbeitsschutz-unternehmen",
  "gefaehrdungsbeurteilung-ablauf": "gefaehrdungsbeurteilung",
  "getraenke-am-arbeitsplatz": "arbeitsschutz-unternehmen",
  "brandschutz-lithium-ionen-batterien": "brandschutz-betrieb",
  "brandschutz-brennbare-stoffe": "brandschutz-betrieb",
  "sigeko-kosten-honorar-orientierung": "sigeko-baustelle",
  "brandschutz-sachverstaendiger-koeln": "brandschutz-betrieb",
  "strafen-arbeitsschutz": "arbeitsschutz-unternehmen",
  "pflichtuebertragung-arbeitsschutz": "arbeitsschutz-unternehmen",
  "brandschutzbeauftragter-aufgaben-pflichten": "brandschutz-betrieb",
  "baustellv-einfach-erklaert": "sigeko-baustelle",
  "baustellv-vorankuendigung-sige-plan": "sigeko-baustelle",
  "baustellv-sigeko-koordination-aufgaben": "sigeko-baustelle",
  "baustellv-anhang-ii-gefaehrliche-arbeiten": "sigeko-baustelle",
  "sigeko-pflicht-wann-braucht-man-sigeko": "sigeko-baustelle",
  "externe-fachkraft-arbeitssicherheit-koeln": "arbeitsschutz-unternehmen",
  "arbeitsschutzberatung-unternehmen": "arbeitsschutz-unternehmen",
  "sicherheitsbeauftragte-schulung-koeln": "arbeitsschutz-unternehmen",
  "arbeitsschutz-dienstleister-nrw": "arbeitsschutz-unternehmen",
  "arbeitsschutzgesetz-arbschg-uebersicht": "arbeitsschutz-unternehmen",
  "arbschg-mehrere-arbeitgeber-zusammenarbeit": "sigeko-baustelle",
  "arbschg-erste-hilfe-notfallmassnahmen": "arbeitsschutz-unternehmen",
  "arbschg-gewerbeaufsicht-begehung-nrw": "arbeitsschutz-unternehmen",
  "brandschutzordnung-din-14096": "brandschutz-betrieb",
  "brandschutzschulungen-unternehmen": "brandschutz-betrieb",
  "gefaehrdungsbeurteilung-schwangere-mutterschutz": "gefaehrdungsbeurteilung",
  "psychische-gefaehrdungsbeurteilung-arbeitsplatz": "gefaehrdungsbeurteilung",
  "betriebsanweisungen-gefahrstoffe": "gefaehrdungsbeurteilung",
  "flucht-und-rettungsplan-erstellen": "brandschutz-betrieb",
  "dguv-vorschrift-3-elektropruefung": "elektrosicherheit-dguv-v3",
  "iso-45001-arbeitsschutzmanagementsystem": "arbeitsschutz-unternehmen",
  "brandschutzkonzept-erstellen": "bauordnung-nrw-brandschutz",
  "vorbeugender-brandschutz-massnahmen": "brandschutz-betrieb",
  "ergonomie-kueche-kita-gefaehrdungsbeurteilung": "gefaehrdungsbeurteilung",
  "sifa-jahresbericht-was-gehoert-rein": "arbeitsschutz-unternehmen",
  "ist-zustandserfassung-externe-fasi": "arbeitsschutz-unternehmen",
  "pruefpflicht-handhubwagen-arbeitssicherheit": "gefaehrdungsbeurteilung",
  "externe-fasi-erstes-vertragsjahr-ablauf": "arbeitsschutz-unternehmen",
  "asa-sitzung-praxis-kita-arbeitsschutz": "arbeitsschutz-unternehmen",
  "unterweisung-arbeitssicherheit-pflicht": "arbeitsschutz-unternehmen",
  "sigeko-begehung-seitenschutz-abbruch-koeln": "sigeko-baustelle",
  "rauchen-baustelle-arbstattv-sigeko": "sigeko-baustelle",
  "gbu-schnittstelle-mehrere-gewerke-bauprojekt": "sigeko-baustelle",
  "sigeko-projektverlauf-neubau-wohngebaeude-nrw": "sigeko-baustelle",
  "sigeko-dacharbeiten-absturz-bestand-koeln": "sigeko-baustelle",
  "sigeko-innenausbau-bestand-leistungsumfang": "sigeko-baustelle",
  "sigeko-koeln-kosten": "sigeko-baustelle",
  "bauordnung-nrw-einfach-erklaert": "bauordnung-nrw-brandschutz",
  "sonderbauverordnung-teil-1-versammlungsstaetten": "bauordnung-nrw-brandschutz",
  "sonderbauverordnung-teil-2-beherbergungsstaetten": "bauordnung-nrw-brandschutz",
  "sonderbauverordnung-teil-3-verkaufsstaetten": "bauordnung-nrw-brandschutz",
  "sonderbauverordnung-teil-4-hochhaeuser": "bauordnung-nrw-brandschutz",
  "sonderbauverordnung-teil-5-garagen": "bauordnung-nrw-brandschutz",
  "sonderbauverordnung-teil-6-elektrische-anlagen": "bauordnung-nrw-brandschutz",
  "sonderbauverordnung-teil-7-schlussvorschriften": "bauordnung-nrw-brandschutz",
  "brandverhuetungsschau-bhkg-nrw": "bhkg-nrw-brandschutz",
  "bma-leitstelle-bhkg-nrw": "bhkg-nrw-brandschutz",
  "brandsicherheitswache-bhkg-nrw": "bhkg-nrw-brandschutz",
  "bhkg-nrw-einfach-erklaert": "bhkg-nrw-brandschutz",
  "baupruefvo-nrw-einfach-erklaert": "bauordnung-nrw-brandschutz",
  "brandschutzkonzept-paragraph-9-baupruefvo": "bauordnung-nrw-brandschutz",
  "brandschutzkonzept-betrieb-brandverhuetungsschau": "bauordnung-nrw-brandschutz",
  "pruefvo-nrw-einfach-erklaert": "brandschutz-betrieb",
  "wirk-prinzip-pruefung-pruefvo-nrw": "brandschutz-betrieb",
  "bma-pruefung-pruefvo-nrw-fristen": "brandschutz-betrieb",
  "sprinkler-rwa-pruefung-pruefvo-nrw": "brandschutz-betrieb",
};

/** Kuratierte Blog-Liste für Pillars ohne eigene blogPillarBySlug-Zuordnung. */
export const pillarFeaturedBlogSlugs: Record<string, string[]> = {
  "bauordnung-nrw-brandschutz": [
    "sprinkler-rwa-pruefung-pruefvo-nrw",
    "bma-pruefung-pruefvo-nrw-fristen",
    "wirk-prinzip-pruefung-pruefvo-nrw",
    "pruefvo-nrw-einfach-erklaert",
    "brandschutzkonzept-betrieb-brandverhuetungsschau",
    "brandschutzkonzept-paragraph-9-baupruefvo",
    "baupruefvo-nrw-einfach-erklaert",
    "brandschutzkonzept-erstellen",
    "bauordnung-nrw-einfach-erklaert",
    "sonderbauverordnung-teil-4-hochhaeuser",
    "sonderbauverordnung-teil-1-versammlungsstaetten",
  ],
  "bhkg-nrw-brandschutz": [
    "bma-pruefung-pruefvo-nrw-fristen",
    "bhkg-nrw-einfach-erklaert",
    "pruefvo-nrw-einfach-erklaert",
    "brandschutzkonzept-betrieb-brandverhuetungsschau",
    "brandsicherheitswache-bhkg-nrw",
    "bma-leitstelle-bhkg-nrw",
    "brandverhuetungsschau-bhkg-nrw",
    "brandschutzbeauftragter-aufgaben-pflichten",
    "flucht-und-rettungsplan-erstellen",
    "brandschutzkonzept-erstellen",
    "sonderbauverordnung-teil-1-versammlungsstaetten",
    "sigeko-pflicht-wann-braucht-man-sigeko",
  ],
  "arbeitsschutz-unternehmen": [
    "arbeitsschutzgesetz-arbschg-uebersicht",
    "arbschg-gewerbeaufsicht-begehung-nrw",
    "arbschg-erste-hilfe-notfallmassnahmen",
    "arbschg-mehrere-arbeitgeber-zusammenarbeit",
    "teilhabe-sgb-ix-einfach-erklaert",
    "sgb-ix-schwerbehindertenvertretung-inklusionsbeauftragter",
    "mutterschutz-muschg-einfach-erklaert",
    "muschg-schutzfristen-arbeitszeit",
    "jugendarbeitsschutz-jarbschg-einfach-erklaert",
    "jarbschg-unterweisung-aushang-dokumentation",
    "jarbschg-arbeitszeit-ruhezeiten",
    "dguv-vorschriften-einfach-erklaert",
    "dguv-vorschrift-1-grundsaetze-praevention",
    "dguv-vorschrift-2",
    "dguv-vorschrift-3-elektropruefung",
    "trbs-einfach-erklaert",
    "trbs-2121-absturz-leitern",
    "asr-einfach-erklaert",
    "asr-a6-bildschirmarbeit",
    "asr-a4-3-erste-hilfe-arbeitsstaette",
    "asr-a2-1-absturz-absturzsicherung",
    "betrsichv-einfach-erklaert",
    "gefaehrdungsbeurteilung-ablauf",
    "unterweisung-arbeitsschutz-fristen",
    "gefaehrdungsbeurteilung-ablauf",
  ],
  "sigeko-baustelle": [
    "baustellv-einfach-erklaert",
    "baustellv-sigeko-koordination-aufgaben",
    "baustellv-vorankuendigung-sige-plan",
    "baustellv-anhang-ii-gefaehrliche-arbeiten",
    "arbschg-mehrere-arbeitgeber-zusammenarbeit",
    "arbeitsschutzgesetz-arbschg-uebersicht",
    "dguv-vorschrift-38-bauarbeiten",
    "dguv-vorschriften-einfach-erklaert",
    "sigeko-pflicht-wann-braucht-man-sigeko",
    "sigeko-dacharbeiten-absturz-bestand-koeln",
    "sigeko-begehung-seitenschutz-abbruch-koeln",
    "gbu-schnittstelle-mehrere-gewerke-bauprojekt",
  ],
  "gefaehrdungsbeurteilung": [
    "arbeitsschutzgesetz-arbschg-uebersicht",
    "teilhabe-sgb-ix-einfach-erklaert",
    "sgb-ix-arbeitsplatz-gestaltung-gbu",
    "sgb-ix-beschaeftigungspflicht-ausgleichsabgabe",
    "mutterschutz-muschg-einfach-erklaert",
    "muschg-unzulaessige-taetigkeiten-schutzmasnahmen",
    "muschg-aushang-mitteilung-dokumentation",
    "muschg-schutzfristen-arbeitszeit",
    "jugendarbeitsschutz-jarbschg-einfach-erklaert",
    "jarbschg-verbotene-gefaehrliche-arbeiten",
    "gefaehrdungsbeurteilung-schwangere-mutterschutz",
    "dguv-vorschriften-einfach-erklaert",
    "dguv-vorschrift-67-flurfoerderzeuge",
    "dguv-vorschrift-1-grundsaetze-praevention",
    "trbs-einfach-erklaert",
    "trbs-1111-gefaehrdungsbeurteilung-arbeitsmittel",
    "trbs-1201-1203-pruefung-befaehigte-person",
    "trbs-2121-absturz-leitern",
    "trgs-einfach-erklaert",
    "trgs-400-gefaehrdungsbeurteilung-gefahrstoffe",
    "trgs-509-510-lagerung-gefahrstoffe",
    "trgs-528-schweisstechnische-arbeiten",
    "betriebsanweisungen-gefahrstoffe",
    "asr-einfach-erklaert",
    "asr-a3-7-laerm-arbeitsplatz",
    "asr-a6-bildschirmarbeit",
    "betrsichv-einfach-erklaert",
    "pruefpflicht-handhubwagen-arbeitssicherheit",
    "gefaehrdungsbeurteilung-ablauf",
    "psychische-gefaehrdungsbeurteilung-arbeitsplatz",
  ],
  "brandschutz-betrieb": [
    "dguv-vorschriften-einfach-erklaert",
    "brandschutzbeauftragter-aufgaben-pflichten",
    "asr-a2-2-brandschutzhelfer",
    "brandschutz-lithium-ionen-batterien",
    "sprinkler-rwa-pruefung-pruefvo-nrw",
    "bma-pruefung-pruefvo-nrw-fristen",
    "wirk-prinzip-pruefung-pruefvo-nrw",
    "pruefvo-nrw-einfach-erklaert",
    "brandschutz-brennbare-stoffe",
    "trgs-509-510-lagerung-gefahrstoffe",
    "trgs-einfach-erklaert",
    "asr-a2-2-brandschutzhelfer",
    "flucht-und-rettungsplan-erstellen",
    "brandschutzbeauftragter-aufgaben-pflichten",
    "brandschutzordnung-din-14096",
    "bma-leitstelle-bhkg-nrw",
    "dguv-vorschrift-3-elektropruefung",
  ],
};

export function getPillarSlugForBlog(slug: string): string | undefined {
  return blogPillarBySlug[slug];
}

/** Andere Blog-Beiträge im selben Pillar-Cluster (max. limit, ohne aktuellen Slug). */
export function getRelatedBlogSlugs(slug: string, limit = 4): string[] {
  const pillar = blogPillarBySlug[slug];
  if (!pillar) return [];
  return Object.entries(blogPillarBySlug)
    .filter(([s, p]) => p === pillar && s !== slug)
    .map(([s]) => s)
    .slice(0, limit);
}

/** Blog-Beiträge, die zu einem Ratgeber-Pillar gehören. */
export function getBlogSlugsForPillar(pillarSlug: string, limit = 5): string[] {
  const featured = pillarFeaturedBlogSlugs[pillarSlug];
  if (featured) return featured.slice(0, limit);
  return Object.entries(blogPillarBySlug)
    .filter(([, p]) => p === pillarSlug)
    .map(([s]) => s)
    .slice(0, limit);
}
